# Generated by Django 4.0.5 on 2023-04-17 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='personal_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(code='correo_invalido', message='El campo debe ser un correo valido', regex="^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$")], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.TextField(choices=[('LE', 'Labora empresa'), ('SO', 'Estudiante'), ('JR', 'Otro')], verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tlf_celular',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='tlf_invalido', message='El campo debe ser un número de teléfono', regex='^\\+?([0-9]{1,3}|[1]\\-?[0-9]{3})?\\-?([0-9]{1,4})\\-?([0-9]{3}\\-?[0-9]{2}\\-?[0-9]{2})$')], verbose_name='Teléfono celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='tlf_whatsapp_invalido', message='El campo debe ser un número de teléfono', regex='^\\+?([0-9]{1,3}|[1]\\-?[0-9]{3})?\\-?([0-9]{1,4})\\-?([0-9]{3}\\-?[0-9]{2}\\-?[0-9]{2})$')], verbose_name='Whatsapp'),
        ),
    ]
