# Generated by Django 4.0.5 on 2023-04-22 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_personal_email_alter_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tlf_celular',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='tlf_invalido', message='El campo debe ser un número de teléfono', regex='^\\+?([0-9]{1,3}|[1]\\-?[0-9]{3})?\\-?([0-9]{1,4})\\-?([0-9]{3}\\-?[0-9]{2}\\-?[0-9]{2})$')], verbose_name='Teléfono celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='tlf_whatsapp_invalido', message='El campo debe ser un número de teléfono', regex='^\\+?([0-9]{1,3}|[1]\\-?[0-9]{3})?\\-?([0-9]{1,4})\\-?([0-9]{3}\\-?[0-9]{2}\\-?[0-9]{2})$')], verbose_name='Whatsapp'),
        ),
    ]
