# Generated by Django 4.0.5 on 2023-06-14 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0005_alter_empleado_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del país')),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='AreaDeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del área de negocio')),
                ('descripcion', models.TextField(verbose_name='Descripción del área de negocio')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_de_negocio', to='empresa.empresa', verbose_name='Empresa relacionada')),
                ('paises', models.ManyToManyField(related_name='areas_de_negocio', to='areadenegocio.pais', verbose_name='Países')),
            ],
            options={
                'verbose_name_plural': 'Áreas de Negocio',
            },
        ),
    ]
