# Generated by Django 4.0.5 on 2023-06-15 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_empleado_ci'),
        ('areadenegocio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areadenegocio',
            name='paises',
        ),
        migrations.AddField(
            model_name='areadenegocio',
            name='pais',
            field=models.TextField(blank=True, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='areadenegocio',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_del_area_de_negocio', to='empresa.empresa', verbose_name='Empresa relacionada'),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
