# Generated by Django 4.0.5 on 2023-04-17 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empleado_ci_alter_empleado_tlf_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cliente_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_empresa', to='empresa.empresa', verbose_name='Cliente de empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(code='correo_invalido', message='El campo debe ser un correo valido', regex="^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$")], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='servicio_ofrecido',
            field=models.TextField(verbose_name='Servicio que le ofrecimos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='tlf_invalido', message='El campo debe ser un número de teléfono', regex='^\\+?([0-9]{1,3}|[1]\\-?[0-9]{3})?\\-?([0-9]{1,4})\\-?([0-9]{3}\\-?[0-9]{2}\\-?[0-9]{2})$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='whatsapp',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='tlf_whatsapp_invalido', message='El campo debe ser un número de teléfono', regex='^\\+?([0-9]{1,3}|[1]\\-?[0-9]{3})?\\-?([0-9]{1,4})\\-?([0-9]{3}\\-?[0-9]{2}\\-?[0-9]{2})$')], verbose_name='Whatsapp'),
        ),
    ]
