# Generated by Django 4.0.5 on 2023-06-14 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empresa_logo_alter_empleado_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ci',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='ci_invalido', message='El campo debe ser una cédula de identidad o número de pasaporte', regex='^(([a-zA-Z]{3}|[a-zA-Z]-)[0-9]{1,3}\\.?[0-9]{1,3}\\.?[0-9]{1,3})$|^([0-9A-Z]{10})$')], verbose_name='Cédula o nro pasaporte'),
        ),
    ]
